services:
  dind:
    container_name: dind
    build:
      context: .
      dockerfile: Dockerfile
      target: host
    privileged: true
    tty: true
    init: true
#    extra_hosts:
#      - dev.yossoi.com:127.0.0.1
#    ports:
#      - 443:443
#    environment:
#      - DOCKER_TLS_CERTDIR=/certs 

