services:
  dind:
    container_name: dind
    build:
      context: .
      dockerfile: Dockerfile
      target: host
    privileged: true
    extra_hosts:
      - dev.yossoi.com=191.168.0.1
    tty: true
    ports:
      - "8080:80"
    network_mode: host
