services:
  go:
#    container_name: go-delivery
    build:
      context: .
      dockerfile: inside.Dockerfile
      target: go-delivery
#    volumes: /run/docker.sock:/run/docker.sock

#    command: ["/run/app"]
#    ports:
#      - "3000:3000"
#    tty: true
#    develop:
#      watch:
#        - action: sync+restart
#          path: ./go-backend/run/app
#          target: /run/app
