services:
  go:
#    container_name: go-delivery
    build:
      context: .
      dockerfile: inside.Dockerfile
      target: go-delivery

#    command: ["/run/app"]
#    ports:
#      - "3000:3000"
#    tty: true
#    develop:
#      watch:
#        - action: sync+restart
#          path: ./go-backend/run/app
#          target: /run/app



## failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: cannot enter cgroupv2 "/sys/fs/cgroup/docker" with domain controllers -- it is in an invalid state: unknown